services:
  test_db:
    image: postgres:17
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - db_test_data:/var/lib/postgresql/data
    networks:
      - test_network

networks:
  test_network:
    driver: bridge

volumes:
  db_test_data: