"""updated author and title

Revision ID: ef8077226530
Revises: c643b6af0ef0
Create Date: 2025-09-17 22:33:01.484200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef8077226530'
down_revision: Union[str, Sequence[str], None] = 'c643b6af0ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('articles_title_key'), 'articles', type_='unique')
    op.drop_index(op.f('ix_articles_author'), table_name='articles')
    op.create_index(op.f('ix_articles_author'), 'articles', ['author'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_author'), table_name='articles')
    op.create_index(op.f('ix_articles_author'), 'articles', ['author'], unique=True)
    op.create_unique_constraint(op.f('articles_title_key'), 'articles', ['title'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
